# SPDX-License-Identifier: AGPL-3.0-only
# Monthly update pull requests, one per ecosystem, so pinned versions don't quietly go stale.
# Security updates (Dependabot alerts) arrive separately, as soon as an advisory is published.
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    groups:
      gradle:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      npm:
        patterns: ["*"]
